### ISSUE TITLE
How to deploy to production

### ISSUE THREAD

**Issue by arufanov** [a5lab/tabr#13]
How to deploy to production

@yurichervoniy 
* could you give me short instruction?

**Comment by yurichervoniy** [comment]
Yeah, for sure
1) Build tabr app using command - ./mvnw clean package
You can also add parameter "-DskipTests" to skip tests - ./mvnw clean package -DskipTests

2) After sucessful build you'll find jar - ./target/tabr-${version}.jar
We'll use it later at step 4

3) Install Java (JRE) on machine (using package manager or copy JRE)
If we want to build lightweight edition of JRE we can use modules - jlink  
For example our custom jre
jlink  --no-header-files \
           --no-man-pages --compress=2 \
           --strip-debug \
           --add-modules java.desktop,java.sql,java.xml,java.naming,java.management \
           --add-modules java.instrument,java.security.jgss,jdk.unsupported,jdk.management,java.rmi \
           --add-modules jdk.naming.dns \
           --output /opt/jre-minified
Or simly install JRE (17) =)
Check that java is corectly installed java using command - java --version

4) Copy tabr-{version}.jar to folder you want on target machine with installed Java from step 3
Install PostgreSQL on target machine - version 14.6 
Create user for DB

To run application use command - 
java  -Dspring.datasource.url=jdbc:postgresql://localhost:5432/tabr -Dspring.datasource.username=tabr -Dspring.datasource.password=tabr_pwd -jar ./target/tabr-0.0.1-SNAPSHOT.jar

**Comment by arufanov** [comment]
-1.sql script
-2.where is log
-3.how to cofigure
-4.systewmd

**Comment by arufanov** [comment]
@yurichervoniy 
* i built by command: mvn clean package -Dmaven.test.skip; result is ok. 
* i run from terminal by command: java -jar ./target/tabr-0.0.1-SNAPSHOT.jar, result is ok
* here is systemd: 
```
#{{ ansible_managed }}
[Unit]
Description=tabr
Wants=postgresql.service
After=network.target local-fs.target postgresql.service

[Service]
Type=forking
User={{ app__user }}
WorkingDirectory={{ app__current_path }}
SyslogIdentifier=tabr
TimeoutSec=5min
Restart=on-failure
RestartSec=5s
ExecStart=java -jar {{ app__current_path }}/target/tabr-0.0.1-SNAPSHOT.jar

[Install]
WantedBy=multi-user.target

```
What is wrong. systemctrl strart tabr hang forever.  Take a look at: https://help.sonatype.com/repomanager3/installation-and-upgrades/run-as-a-service

**Comment by arufanov** [comment]
https://www.baeldung.com/linux/run-java-application-as-service

**Comment by arufanov** [comment]
@yurichervoniy 
* https://www.baeldung.com/linux/run-java-application-as-service help me, but systemctr stop tabr produces 
```
ot@tabr:~# systemctl status tabr.service
× tabr.service - tabr
     Loaded: loaded (/etc/systemd/system/tabr.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-11-27 21:36:11 UTC; 2s ago
    Process: 111801 ExecStart=java -jar /home/tabr/current/target/tabr-0.0.1-SNAPSHOT.jar (code=exited, status=143)
    Process: 111833 ExecStop=/bin/kill -15 $MAINPID (code=exited, status=0/SUCCESS)
   Main PID: 111801 (code=exited, status=143)
        CPU: 10.171s
```

code=exited, status=143. I suppose, that is not ok

**Comment by arufanov** [comment]
root@tabr:~# java -jar /home/tabr/current/target/tabr-0.0.1-SNAPSHOT.jar
Logging system failed to initialize using configuration from 'null'
java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(/tmp/spring.log,true) call failed. java.io.FileNotFoundException: /tmp/spring.log (Permission denied)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:251)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:186)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:332)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:352)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)

**Comment by arufanov** [comment]
install postgresq. java -Dspring.datasource.password=secret -jar ./target/tabr-0.0.1-SNAPSHOT.jar
